  version: '3.1'

  services: 
    mysql: 
      image: mysql:8.0
      container_name: my_mysql_container
      ports: 
        - "3306:3306"
      restart: on-failure
      environment:
        MYSQL_DATABASE: meng_admin
        MYSQL_ROOT_PASSWORD: admin123
      volumes:
        - mysql_data:/var/lib/mysql

    redis:
      image: redis:latest
      ports:
          - "6379:6379"

    minio:
      image: bitnami/minio:latest
      ports:
        - "9000:9000"
        - "9001:9001"
      environment: 
        MINIO_ACCESS_KEY: minio
        MINIO_SECRET_KEY: minio@123
      volumes:
        - 'minio_data:/bitnami/minio/data'
        

  volumes:
    mysql_data: 
    minio_data:
      driver: local

